
package at.co.svc.soap.client.verstaendigungenAbfragen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SEVerstaendigungenAbfragenService", targetNamespace = "http://www.sozialversicherung.at/schema/zpv/ibs/VerstaendigungenAbfragen_3_0", wsdlLocation = "file:/C:/tmp/learn_quarkus/%5B05a%5D%20quarkus-code-jax-ws-java/src/main/resources/wsdl/SEVerstaendigungenAbfragen.wsdl")
public class SEVerstaendigungenAbfragenService
    extends Service
{

    private final static URL SEVERSTAENDIGUNGENABFRAGENSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEVERSTAENDIGUNGENABFRAGENSERVICE_EXCEPTION;
    private final static QName SEVERSTAENDIGUNGENABFRAGENSERVICE_QNAME = new QName("http://www.sozialversicherung.at/schema/zpv/ibs/VerstaendigungenAbfragen_3_0", "SEVerstaendigungenAbfragenService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/tmp/learn_quarkus/%5B05a%5D%20quarkus-code-jax-ws-java/src/main/resources/wsdl/SEVerstaendigungenAbfragen.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEVERSTAENDIGUNGENABFRAGENSERVICE_WSDL_LOCATION = url;
        SEVERSTAENDIGUNGENABFRAGENSERVICE_EXCEPTION = e;
    }

    public SEVerstaendigungenAbfragenService() {
        super(__getWsdlLocation(), SEVERSTAENDIGUNGENABFRAGENSERVICE_QNAME);
    }

    public SEVerstaendigungenAbfragenService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEVERSTAENDIGUNGENABFRAGENSERVICE_QNAME, features);
    }

    public SEVerstaendigungenAbfragenService(URL wsdlLocation) {
        super(wsdlLocation, SEVERSTAENDIGUNGENABFRAGENSERVICE_QNAME);
    }

    public SEVerstaendigungenAbfragenService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEVERSTAENDIGUNGENABFRAGENSERVICE_QNAME, features);
    }

    public SEVerstaendigungenAbfragenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SEVerstaendigungenAbfragenService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerstaendigungenAbfragen
     */
    @WebEndpoint(name = "VerstaendigungenAbfragenPort")
    public VerstaendigungenAbfragen getVerstaendigungenAbfragenPort() {
        return super.getPort(new QName("http://www.sozialversicherung.at/schema/zpv/ibs/VerstaendigungenAbfragen_3_0", "VerstaendigungenAbfragenPort"), VerstaendigungenAbfragen.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerstaendigungenAbfragen
     */
    @WebEndpoint(name = "VerstaendigungenAbfragenPort")
    public VerstaendigungenAbfragen getVerstaendigungenAbfragenPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sozialversicherung.at/schema/zpv/ibs/VerstaendigungenAbfragen_3_0", "VerstaendigungenAbfragenPort"), VerstaendigungenAbfragen.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEVERSTAENDIGUNGENABFRAGENSERVICE_EXCEPTION!= null) {
            throw SEVERSTAENDIGUNGENABFRAGENSERVICE_EXCEPTION;
        }
        return SEVERSTAENDIGUNGENABFRAGENSERVICE_WSDL_LOCATION;
    }

}
