
package at.itsv.eaum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EAUMPortType", targetNamespace = "http://eaum.itsv.at")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EAUMPortType {


    /**
     * 
     * @param meldungRequest
     * @return
     *     returns at.itsv.eaum.MeldungResponse
     */
    @WebMethod(operationName = "Meldung", action = "Meldung")
    @WebResult(name = "MeldungResponse", targetNamespace = "http://www.itsv.at/eAUM/", partName = "MeldungResponse")
    public MeldungResponse meldung(
        @WebParam(name = "MeldungRequest", targetNamespace = "http://www.itsv.at/eAUM/", partName = "MeldungRequest")
        MeldungRequest meldungRequest);

}
