
package at.itsv.eaum;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EAUM", targetNamespace = "http://eaum.itsv.at", wsdlLocation = "/at/itsv/eaum/wsdl/eAUM_V3_0_1.wsdl")
public class EAUM
    extends Service
{

    private final static URL EAUM_WSDL_LOCATION;
    private final static WebServiceException EAUM_EXCEPTION;
    private final static QName EAUM_QNAME = new QName("http://eaum.itsv.at", "EAUM");

    static {
        EAUM_WSDL_LOCATION = at.itsv.eaum.EAUM.class.getResource("/at/itsv/eaum/wsdl/eAUM_V3_0_1.wsdl");
        WebServiceException e = null;
        if (EAUM_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/at/itsv/eaum/wsdl/eAUM_V3_0_1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        EAUM_EXCEPTION = e;
    }

    public EAUM() {
        super(__getWsdlLocation(), EAUM_QNAME);
    }

    public EAUM(WebServiceFeature... features) {
        super(__getWsdlLocation(), EAUM_QNAME, features);
    }

    public EAUM(URL wsdlLocation) {
        super(wsdlLocation, EAUM_QNAME);
    }

    public EAUM(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EAUM_QNAME, features);
    }

    public EAUM(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAUM(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EAUMPortType
     */
    @WebEndpoint(name = "EAUMHttpPort")
    public EAUMPortType getEAUMHttpPort() {
        return super.getPort(new QName("http://eaum.itsv.at", "EAUMHttpPort"), EAUMPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EAUMPortType
     */
    @WebEndpoint(name = "EAUMHttpPort")
    public EAUMPortType getEAUMHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eaum.itsv.at", "EAUMHttpPort"), EAUMPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EAUM_EXCEPTION!= null) {
            throw EAUM_EXCEPTION;
        }
        return EAUM_WSDL_LOCATION;
    }

}
